#!/bin/sh
#
# nginx Start and stop nginx
#
# chkconfig: 2345 80 20
# description: Nginx server

### BEGIN INIT INFO
# Provides: nginx
# Required-Start: $remote_fs $network
# Required-Stop: $remote_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start and stop nginx
### END INIT INFO

prog=nginx
base=/usr/local/nginx
exec=$base/sbin/nginx
pidfile=$base/logs/$prog.pid
lockfile=/var/lock/subsys/$prog
retval=0

[ -x $exec ] || exit 5

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

. /etc/rc.d/init.d/functions

configtest() {
	res=$($exec -t 2>&1)
	retval=$?
	if [ -z "$1" ]; then
		res="\n$res"
	fi
	if [ -n "$1" ] || [ $retval != 0 ]; then
		echo -ne "$res"
	fi
	return $retval
}

start() {
	daemon --pidfile=$pidfile $exec
	retval=$?
	[ $retval == 0 ] && touch $lockfile
	return $retval
}

stop() {
	killproc -p $pidfile $prog
	retval=$?
	[ $retval = 0 ] && rm -f $lockfile
	return $retval
}

stat() {
	res=$(status -p $pidfile $prog 2>&1)
	retval=$?
	[ -n "$1" ] && echo $res
	return $retval
}

restart() {
	echo -n "Restarting $prog: "
	configtest && stop && start
	echo
}

case "$1" in
	start)
		stat && exit 0
		echo -n "Starting $prog: "
		start
		echo
		;;
	stop)
		stat || exit 0
		echo -n "Stopping $prog: "
		stop
		echo
		;;
	restart|force-reload)
		restart
		;;
	condrestart|try-restart)
		stat || exit 0
		restart
		;;
	reload)
		stat || exit 7
		echo -n "Reloading $prog: "
		configtest && killproc -p $pidfile $prog -HUP
		retval=$?
		echo
		;;
	status)
		stat 1
		;;
	configtest)
		configtest 1
		echo
		;;
	flushlogs)
		stat || exit 7
		echo -n "Flushing $prog logs: "
		killproc -p $pidfile $prog -USR1
		retval=$?
		echo
		;;
	*)
		echo "Usage: $0 {start|stop|restart|condrestart|try-restart|reload|force-reload|status|configtest|flushlogs}" >&2
		retval=2
		;;
esac

exit $retval
