#!/bin/sh
### BEGIN INIT INFO
# Provides: nginx
# Required-Start: $remote_fs $network
# Required-Stop: $remote_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start and stop nginx
### END INIT INFO

NAME=nginx
DESC="Nginx server"
PATH=/sbin:/usr/sbin:/bin:/usr/bin
BASE=/usr/local/nginx
DAEMON=$BASE/sbin/nginx
PIDFILE=$BASE/logs/$NAME.pid
RETVAL=0

[ -x $DAEMON ] || exit 0

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

. /lib/init/vars.sh

. /lib/lsb/init-functions

configtest() {
	res=$($DAEMON -t 2>&1)
	RETVAL=$?
	if [ -z "$1" ]; then
		res="\n$res"
	fi
	if [ -n "$1" ] || [ $RETVAL != 0 ]; then
		echo -e "$res"
	fi
	return $RETVAL
}

start() {
	flag=--oknodo && [ -z "$1" ] && flag=
	start-stop-daemon --start $flag --quiet --pidfile $PIDFILE --exec $DAEMON
	RETVAL=$?
	return $RETVAL
}

stop() {
	start-stop-daemon --stop --oknodo --quiet --pidfile $PIDFILE
	RETVAL=$?
	return $RETVAL
}

case "$1" in
	start)
		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
		start 1
		[ "$VERBOSE" != no ] && log_end_msg $RETVAL
		;;
	stop)
		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
		stop
		[ "$VERBOSE" != no ] && log_end_msg $RETVAL
		;;
	restart|force-reload)
		log_daemon_msg "Restarting $DESC" "$NAME"
		configtest && stop && start
		log_end_msg $RETVAL
		;;
	reload)
		log_daemon_msg "Reloading $DESC" "$NAME"
		configtest && start-stop-daemon --stop --signal HUP --quiet --pidfile $PIDFILE
		RETVAL=$?
		log_end_msg $RETVAL
		;;
	status)
		status_of_proc -p $PIDFILE $DAEMON $NAME
		RETVAL=$?
		;;
	configtest)
		configtest 1
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload|force-reload|status|configtest}" >&2
		RETVAL=2
		;;
esac

exit $RETVAL
